### ISSUE TITLE
Flutter Android Force Closed because if Key is not initialized in Android 14

### ISSUE THREAD

**Issue by arifinreinaldo** [umkithya/google_map_dynamic_key#2]
Failed to handle method call
E/MethodChannel#flutter/platform_views( 9025): java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
E/MethodChannel#flutter/platform_views( 9025): 	at com.google.maps.api.android.lib6.common.c.b(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:109)
E/MethodChannel#flutter/platform_views( 9025): 	at com.google.android.gms.maps.internal.CreatorImpl.c(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:465)
E/MethodChannel#flutter/platform_views( 9025): 	at com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:23)
E/MethodChannel#flutter/platform_views( 9025): 	at com.google.android.gms.maps.internal.h.bs(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:273)
E/MethodChannel#flutter/platform_views( 9025): 	at m.aya.onTransact(:com.google.android.gms.policy_maps_core_dynamite@244125205@244125202025.684868338.684868338:21)
E/MethodChannel#flutter/platform_views( 9025): 	at android.os.Binder.transact(Binder.java:1219)
E/MethodChannel#flutter/platform_views( 9025): 	at com.google.android.gms.internal.maps.zza.zzJ(com.google.android.gms:play-services-maps@@18.2.0:2)
E/MethodChannel#flutter/platform_views( 9025): 	at com.google.android.gms.maps.internal.zze.zzg(com.google.android.gms:play-services-maps@@18.2.0:4)
E/MethodChannel#flutter/platform_views( 9025): 	at com.google.android.gms.maps.zzai.zzb(com.google.android.gms:play-services-maps@@18.2.0:4)
E/MethodChannel#flutter/platform_views( 9025): 	at com.google.android.gms.maps.zzai.createDelegate(com.google.android.gms:play-services-maps@@18.2.0:1)
E/MethodChannel#flutter/platform_views( 9025): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaf(com.google.android.gms:play-services-base@@18.3.0:6)
E/MethodChannel#flutter/platform_views( 9025): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(com.google.android.gms:play-services-base@@18.3.0:1)
E/MethodChannel#flutter/platform_views( 9025): 	at com.google.android.gms.maps.MapView.onCreate(com.google.android.gms:play-services-maps@@18.2.0:4)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.plugins.googlemaps.GoogleMapController.onCreate(GoogleMapController.java:436)
E/MethodChannel#flutter/platform_views( 9025): 	at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:24)
E/MethodChannel#flutter/platform_views( 9025): 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:322)
E/MethodChannel#flutter/platform_views( 9025): 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:199)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.plugins.googlemaps.GoogleMapController.init(GoogleMapController.java:177)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.plugins.googlemaps.GoogleMapBuilder.build(GoogleMapBuilder.java:41)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.plugins.googlemaps.GoogleMapFactory.create(GoogleMapFactory.java:69)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:523)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views( 9025): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views( 9025): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#flutter/platform_views( 9025): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views( 9025): 	at android.os.Looper.loopOnce(Looper.java:230)
E/MethodChannel#flutter/platform_views( 9025): 	at android.os.Looper.loop(Looper.java:319)
E/MethodChannel#flutter/platform_views( 9025): 	at android.app.ActivityThread.main(ActivityThread.java:8919)
E/MethodChannel#flutter/platform_views( 9025): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 9025): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
E/MethodChannel#flutter/platform_views( 9025): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

Need to close the app once to be able to use it

**Comment by arifinreinaldo** [comment]
Manage to solve this issue by  changing the order, getting the location permission first then adding the key function
